services:
  mongodb:
    image: mongo:8
    container_name: yelpcamp-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=yelpCamp

  app:
    build: .
    container_name: yelpcamp-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/yelpCamp
    depends_on:
      - mongodb

volumes:
  mongodb_data: