name: Deploy to Staging

on:
  push:
    branches: [staging]
  workflow_dispatch:  # Allow manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image for testing
        run: docker build -t yelp-camp:test .

      - name: Start app container for testing
        run: |
          docker run -d \
            --name app-container \
            -p 3000:3000 \
            -e MONGO_PASSWORD="${{ secrets.MONGO_PASSWORD }}" \
            -e DEV_DB="${{ secrets.DEV_DB }}" \
            -e NODE_ENV="development" \
            yelp-camp:test

      - name: Wait for application to be ready
        run: |
          echo "Waiting for app to start..."
          timeout 60 bash -c '
            until curl -f http://localhost:3000 > /dev/null 2>&1; do 
              echo "App not ready, waiting..."
              sleep 3
            done
          '
          echo "App is ready!"

      - name: Run tests
        run: |
          docker exec app-container npm run tests

      - name: Stop and remove test containers
        if: always()
        run: |
          docker stop app-container || true
          docker rm app-container || true

  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/yelp-camp
          tags: |
            type=raw,value=staging
            type=sha,prefix=staging-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trigger Render deployment
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            https://api.render.com/v1/services/${{ secrets.RENDER_STAGING_SERVICE_ID }}/deploys

      - name: Update commit status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Staging deployment successful"
          else
            echo "❌ Staging deployment failed"
            exit 1
          fi