name: Staging Branch Tests

on:
  pull_request:
    branches: [staging]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t yelp-camp:test .

      - name: Run tests in container
        run: |
          docker run --rm \
            -e CI=true \
            -e PLAYWRIGHT_BROWSERS_PATH=/usr/bin/chromium-browser \
            -v ${{ github.workspace }}/playwright-report:/app/playwright-report \
            yelp-camp:test \
            npm run tests

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30